apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Yossi-Cohen19/Chaos-App-Project.git
    targetRevision: develop
    path: charts/chaos-generic
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: chaos-dev.example.com
        - name: clusterSecretStore.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Yossi-Cohen19/Chaos-App-Project.git
    targetRevision: develop
    path: charts/chaos-generic
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: chaos-staging.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
