apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Yossi-Cohen19/Chaos-App-Project.git
    targetRevision: main
    path: charts/chaos-generic
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: chaos-prod.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
