apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Yossi-Cohen19/Chaos-App-Project.git
    targetRevision: main
    path: argocd-apps/apps
    directory:
      recurse: true
      include: '{infrastructure/*,workloads/prod/*}'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
